name: jagoentertainment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: any
  get: ^4.7.2
  logger: ^2.6.0
  fluttertoast: ^8.2.12
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  phosphor_flutter: ^2.1.0
  dio: ^5.9.0
  package_info_plus: ^8.3.1
  pinput: ^5.0.1
  carousel_slider: ^5.1.1
  youtube_player_flutter: ^9.1.3
  audio_service: ^0.18.18
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  youtube_explode_dart: ^2.5.2
  youtube_player_iframe: ^5.2.2
  animate_do: ^4.2.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  video_player: ^2.10.1
  chewie: ^1.13.0
  better_player_plus: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4  # â† Correct placement


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logonew.jpg"
  # Optional: For adaptive icons
  # adaptive_icon_background: "#FF0000"  # Red background
  # adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic